services:
  backend:
    build: ./packages/backend
    ports:
      - "8080:8080"

  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./packages/frontend/.env
    depends_on:
      - backend
