services:
  backend:
    build: ./packages/backend
    env_file:
      - ./packages/backend/.env
    depends_on:
      - redis

  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    env_file:
      - ./packages/frontend/.env
    depends_on:
      - backend

  redis:
    image: redis:7-alpine