services:
  backend:
    build: ./packages/backend

  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    env_file:
      - ./packages/frontend/.env
    depends_on:
      - backend
